openapi: "3.0.1"

info:
  title: "merged spec"
  description: "merged spec"
  version: "1.0.0"

servers:
  - url: "http://localhost:8080"
    description: "Servidor de Desarrollo Local"

tags:
  - name: Customer
    description: "Operaciones relacionadas con los clientes"
  - name: Product
    description: "Operaciones relacionadas con los productos del catálogo"
  - name: Shop
    description: "Operaciones relacionadas con las tiendas y su inventario"
  - name: Shop Product Offering
    description: "Operaciones para gestionar qué productos se ofrecen en qué tiendas y a qué precio"
  - name: Purchase
    description: "Operaciones relacionadas con las compras de los clientes (carritos y pedidos)"

paths:

  /customers:
    $ref: "./customer.yml#/paths/~1customers"
  /customers/{customerId}:
    $ref: "./customer.yml#/paths/~1customers~1{customerId}"


  /products:
    $ref: "./product.yml#/paths/~1products"
  /products/{productId}:
    $ref: "./product.yml#/paths/~1products~1{productId}"


  /purchases:
    $ref: "./purchase.yml#/paths/~1purchases"
  /purchases/{purchaseId}:
    $ref: "./purchase.yml#/paths/~1purchases~1{purchaseId}"
  /purchases/{purchaseId}/productInShop/{productInShopId}:
    $ref: "./purchase.yml#/paths/~1purchases~1{purchaseId}~1productInShop~1{productInShopId}"
  /purchases/{purchaseId}/finish:
    $ref: "./purchase.yml#/paths/~1purchases~1{purchaseId}~1finish"


  /shops:
    $ref: "./shop.yml#/paths/~1shops"
  /shops/{shopId}:
    $ref: "./shop.yml#/paths/~1shops~1{shopId}"
  /shops/{shopId}/products/{productId}:
    $ref: "./shop.yml#/paths/~1shops~1{shopId}~1products~1{productId}"
